Repository tmc-coach/tmc-coach, pull requests merged in 2023-04, with the labels that each got.

#190 delete unnecessary code
  frontend/cypress/e2e/courses.cy.js
  frontend/cypress/e2e/exercises.cy.js
  frontend/cypress/e2e/header_and_signout.cy.js
  frontend/cypress/e2e/login.cy.js
  frontend/cypress/e2e/organizations.cy.js
  frontend/cypress/e2e/set_deadline.cy.js
  frontend/src/components/Deadlines.js
Labels: draft

#201 add coverage plugin
  backend/.coveragerc
  backend/README.md
  backend/requirements.txt
Labels: help wanted, draft

#226 Feat async email
  backend/app/__init__.py
  backend/modules/email.py
Labels: untested

#231 Feat choosing target points
  backend/modules/deadline.py
  backend/pages/deadline.py
  backend/tests/database_functions_test.py
  frontend/cypress/e2e/set_deadline.cy.js
  frontend/src/components/Deadline.js
  frontend/src/components/Deadlines.js
  frontend/src/components/Exercises.js
  frontend/src/components/SetDeadline.js
Labels: ready for approval
